### ISSUE TITLE
Models not working

### ISSUE THREAD

**Issue by ErnieBoxer** [dusty-nv/jetson-voice#2]
I can run tests and they pass but if I attempt to run anything else they fail.

`
@jetson:/jetson-voice/examples# ./asr.py --wav data/audio/dusty.wav
Namespace(debug=False, default_backend='tensorrt', global_config=None, list_devices=False, list_models=False, log_level='info', mic=None, model='quartznet', model_dir='data/networks', model_manifest='data/networks/manifest.json', profile=False, verbose=False, wav='data/audio/dusty.wav')
Traceback (most recent call last):
  File "./asr.py", line 25, in <module>
    asr = ASR(args.model)
  File "/jetson-voice/jetson_voice/asr.py", line 18, in ASR
    return load_resource(resource, factory_map, *args, **kwargs)
  File "/jetson-voice/jetson_voice/utils/resource.py", line 57, in load_resource
    manifest = download_model(resource)
  File "/jetson-voice/jetson_voice/utils/resource.py", line 166, in download_model
    manifest = find_model_manifest(name)
  File "/jetson-voice/jetson_voice/utils/resource.py", line 143, in find_model_manifest
    manifest = load_models_manifest()
  File "/jetson-voice/jetson_voice/utils/resource.py", line 128, in load_models_manifest
    with open(path) as file:
FileNotFoundError: [Errno 2] No such file or directory: 'data/networks/manifest.json'

`

`PASSED TEST test_tts.py (fastpitch_hifigan) - return code 0

----------------------------------------------------
 TEST SUMMARY
----------------------------------------------------
test_asr.py (quartznet)                  PASSED
test_asr.py (quartznet_greedy)           PASSED
test_asr.py (matchboxnet)                PASSED
test_asr.py (vad_marblenet)              PASSED
test_nlp.py (distilbert_qa_128)          PASSED
test_nlp.py (distilbert_qa_384)          PASSED
test_nlp.py (distilbert_intent)          PASSED
test_nlp.py (distilbert_sentiment)       PASSED
test_nlp.py (distilbert_ner)             PASSED
test_tts.py (fastpitch_hifigan)          PASSED

passed 10 of 10 tests`

**Comment by ErnieBoxer** [comment]
Working on old system sd san mic which does not work.
