### ISSUE TITLE
Killed

### ISSUE THREAD

**Issue by AdamMiltonBarker** [dusty-nv/jetson-voice#4]
Hi Dusty I was interested to see how your model compared to the official intent and slots example as it was not classifying the slots in the examples after 100 epochs and performed poorly on additional inputs. 

I experienced the following issue on Jetson Nano  4gb, Jetpack  4.5.1-b17

```
[TensorRT] VERBOSE: After vertical fusions: 250 layers
[TensorRT] VERBOSE: After final dead-layer removal: 250 layers
[TensorRT] VERBOSE: After tensor merging: 250 layers
[TensorRT] VERBOSE: After concat removal: 250 layers
[TensorRT] VERBOSE: Graph construction and optimization completed in 0.934568 seconds.
[TensorRT] VERBOSE: Constructing optimization profile number 0 [1/1].
[TensorRT] VERBOSE: *************** Autotuning format combination:  -> Float(1,768) ***************
[TensorRT] VERBOSE: *************** Autotuning format combination:  -> Half(1,768) ***************
Killed
```

**Comment by AdamMiltonBarker** [comment]
It managed to get past that after a number of retries, then I was faced with the followin: 

```
built engine in 161.7185652256012 seconds

----------------------------------------------------
 BUILDER CONFIGURATION
----------------------------------------------------
  - model     /jetson-voice/data/networks/nlp/distilbert_intent/distilbert_intent.onnx
  - config    /jetson-voice/data/networks/nlp/distilbert_intent/distilbert_intent.json
  - output    /jetson-voice/data/networks/nlp/distilbert_intent/distilbert_intent.engine
  - type      intent_slot
  - layers    1055
  - inputs    2
  - outputs   2
  - precision fp16
  - workspace 128

  - input 0:
      - name     input_ids
      - shape    (-1, -1)
      - dtype    DataType.INT32
  - input 1:
      - name     attention_mask
      - shape    (-1, -1)
      - dtype    DataType.INT32
  - output 0:
      - name     intent_logits
      - shape    (-1, 64)
      - dtype    DataType.FLOAT
  - output 1:
      - name     slot_logits
      - shape    (-1, -1, 55)
      - dtype    DataType.FLOAT

serializing engine...
[TensorRT] ERROR: FAILED_ALLOCATION: std::bad_alloc
Traceback (most recent call last):
  File "examples/nlp.py", line 17, in <module>
    model = NLP(args.model)
  File "/jetson-voice/jetson_voice/nlp.py", line 18, in NLP
    return AutoModel(resource, domain='nlp', *args, **kwargs)
  File "/jetson-voice/jetson_voice/auto.py", line 46, in AutoModel
    return type_map[config.type][0](config, *args, **kwargs)
  File "/jetson-voice/jetson_voice/nlp.py", line 31, in IntentSlot
    return load_resource(resource, factory_map, *args, **kwargs)
  File "/jetson-voice/jetson_voice/utils/resource.py", line 85, in load_resource
    return class_type(config, *args, **kwargs)
  File "/jetson-voice/jetson_voice/models/nlp/intent_slot.py", line 34, in __init__
    self.model = load_model(self.config, dynamic_shapes)
  File "/jetson-voice/jetson_voice/utils/resource.py", line 117, in load_model
    return class_type(config, dynamic_shapes=dynamic_shapes)
  File "/jetson-voice/jetson_voice/backends/tensorrt/trt_model.py", line 47, in __init__
    self.trt_engine = build_engine(self.config, dynamic_shapes=dynamic_shapes)
  File "/jetson-voice/jetson_voice/backends/tensorrt/trt_builder.py", line 175, in build_engine
    engine_file.write(serialized_engine)
TypeError: a bytes-like object is required, not 'NoneType'
root@nvidia-jetson-nano-1:/jetson-voice# examples/nlp.py --model distilbert_intent
Namespace(debug=False, default_backend='tensorrt', global_config=None, list_models=False, log_level='info', model='distilbert_intent', model_dir='/jetson-voice/data/networks', model_manifest='/jetson-voice/data/networks/manifest.json', profile=False, verbose=False)
[2021-08-22 16:52:10] resource.py:114 - loading model '/jetson-voice/data/networks/nlp/distilbert_intent/distilbert_intent.onnx' with jetson_voice.backends.tensorrt.TRTModel
[2021-08-22 16:52:10] trt_model.py:41 - loading cached TensorRT engine from /jetson-voice/data/networks/nlp/distilbert_intent/distilbert_intent.engine
[TensorRT] ERROR: INVALID_ARGUMENT: Cannot deserialize with an empty memory buffer.
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
Traceback (most recent call last):
  File "examples/nlp.py", line 17, in <module>
    model = NLP(args.model)
  File "/jetson-voice/jetson_voice/nlp.py", line 18, in NLP
    return AutoModel(resource, domain='nlp', *args, **kwargs)
  File "/jetson-voice/jetson_voice/auto.py", line 46, in AutoModel
    return type_map[config.type][0](config, *args, **kwargs)
  File "/jetson-voice/jetson_voice/nlp.py", line 31, in IntentSlot
    return load_resource(resource, factory_map, *args, **kwargs)
  File "/jetson-voice/jetson_voice/utils/resource.py", line 85, in load_resource
    return class_type(config, *args, **kwargs)
  File "/jetson-voice/jetson_voice/models/nlp/intent_slot.py", line 34, in __init__
    self.model = load_model(self.config, dynamic_shapes)
  File "/jetson-voice/jetson_voice/utils/resource.py", line 117, in load_model
    return class_type(config, dynamic_shapes=dynamic_shapes)
  File "/jetson-voice/jetson_voice/backends/tensorrt/trt_model.py", line 56, in __init__
    raise IOError(f'failed to load TensorRT engine from {self.model_path}')
AttributeError: 'TRTModel' object has no attribute 'model_path'
```
then
```
[2021-08-22 16:54:11] resource.py:114 - loading model '/jetson-voice/data/networks/nlp/distilbert_intent/distilbert_intent.onnx' with jetson_voice.backends.tensorrt.TRTModel
[2021-08-22 16:54:11] trt_model.py:41 - loading cached TensorRT engine from /jetson-voice/data/networks/nlp/distilbert_intent/distilbert_intent.engine
[TensorRT] ERROR: INVALID_ARGUMENT: Cannot deserialize with an empty memory buffer.
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
Traceback (most recent call last):
  File "examples/nlp.py", line 17, in <module>
    model = NLP(args.model)
  File "/jetson-voice/jetson_voice/nlp.py", line 18, in NLP
    return AutoModel(resource, domain='nlp', *args, **kwargs)
  File "/jetson-voice/jetson_voice/auto.py", line 46, in AutoModel
    return type_map[config.type][0](config, *args, **kwargs)
  File "/jetson-voice/jetson_voice/nlp.py", line 31, in IntentSlot
    return load_resource(resource, factory_map, *args, **kwargs)
  File "/jetson-voice/jetson_voice/utils/resource.py", line 85, in load_resource
    return class_type(config, *args, **kwargs)
  File "/jetson-voice/jetson_voice/models/nlp/intent_slot.py", line 34, in __init__
    self.model = load_model(self.config, dynamic_shapes)
  File "/jetson-voice/jetson_voice/utils/resource.py", line 117, in load_model
    return class_type(config, dynamic_shapes=dynamic_shapes)
  File "/jetson-voice/jetson_voice/backends/tensorrt/trt_model.py", line 56, in __init__
    raise IOError(f'failed to load TensorRT engine from {self.model_path}')
AttributeError: 'TRTModel' object has no attribute 'model_path'
```
